### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by TaeilJin** [loco-3d/multicontact-locomotion-planning#45]
Hi
I use python 3.6 and ubuntu 18.04.
I installed dependencies like this way.
"sudo apt update && sudo apt install robotpkg-py36-pinocchio robotpkg-py36-multicontact-api"

After that, there is a error message when I import pinocchio.

![image](https://user-images.githubusercontent.com/41664042/81308990-6707bb00-90bd-11ea-9a45-927ab2c3171d.png)

hppfcl is installed, but there is no libhpp-fcl.so in the folder
/opt/openrobots/lib/python3.6/site-packages/hppfcl/

**Comment by pFernbach** [comment]
Hello, the libhpp-fcl.so should be in `/opt/openrobots/lib/`. If it is, you should add this path to your `LD_LIBRARY_PATH`.

**Comment by TaeilJin** [comment]
Thank you so much, 

But there is no libhpp-fcl.so in /opt/opentobots/lib too.

![image](https://user-images.githubusercontent.com/41664042/81310910-ad5e1980-90bf-11ea-8053-c5118da1da6e.png)

**Comment by pFernbach** [comment]
Ok, I think you can try to install  `robotpkg-hpp-fcl` but It should have been a dependency of pinocchio. I will let @nim65s check this.

**Comment by nim65s** [comment]
Hi @TaeilJin,

I can confirm that on a clear configuration, after only a 
`sudo apt update && sudo apt install robotpkg-py36-pinocchio robotpkg-py36-multicontact-api`

I can run
```
$ dpkg -S /opt/openrobots/lib/libhpp-fcl.so
robotpkg-hpp-fcl+doc: /opt/openrobots/lib/libhpp-fcl.so
```

Which mean that hpp-fcl is correctly installed and its lib is present.

**Comment by nim65s** [comment]
So I don't understand your problem. Maybe you can try to re-install it : `sudo apt install -qqy robotpkg-hpp-fcl`

**Comment by TaeilJin** [comment]
I have another error message after install robotpkg-hpp-fcl 
"there is no liboctomap.so.1.9" 
It seems that error is came from my side. 

I erased openrobots folder for clearing configurations, it was my mistake, and then there were a lot of errors came up. 
I suppose that those errors are result from my mistakes.

**Comment by TaeilJin** [comment]
I suppose that you can close this issue. 

Anyway thank you so much for quick responses.

**Comment by nim65s** [comment]
if you need to clean it:

```
sudo apt remove robotpkg-\*
sudo rm -rf /opt/openrobots
sudo apt install robotpkg-py36-pinocchio robotpkg-py36-multicontact-api
```

That should fix the issues with your configuration :)

**Comment by TaeilJin** [comment]
I solve the error!
Removing whole packages was a answer ;)
 
I tried to remove robotpkg-octomap which is not installed in openrobots folder, and then whole packages were automatically removed. After that, installation was worked.

I will follow your comments if I try to clear my configurations.
I am a beginner, so your comments are really helped me.
Thank you so much.

**Comment by TaeilJin** [comment]
Can I ask one thing?

I am trying to use python 3 and install devel branch.

After installing whole dependencies, I am trying to do cmake.

And there is a error message in command line.

![image](https://user-images.githubusercontent.com/41664042/81502985-2a85ca80-931c-11ea-8435-4a823b3e29ba.png)

Do I have to copy and paste the cmake folder manually?

**Comment by wxmerkt** [comment]
Run ``git submodule update --init --recursive`` - this will clone the submodule.

**Comment by TaeilJin** [comment]
Thank you so much!

After that, there is another error message.

![image](https://user-images.githubusercontent.com/41664042/81504351-9ddf0a80-9323-11ea-8eee-d9c97a86e678.png)

**Comment by wxmerkt** [comment]
The code to set the version was recently changed. I am not sure whether the cmake submodule has been updated since. You might try to `cd cmake ; git fetch ; git checkout master` to update the cmake submodule.

**Comment by TaeilJin** [comment]
Thank you for quick response.

It seems not working 

There is another error message.

![image](https://user-images.githubusercontent.com/41664042/81505313-35932780-9329-11ea-8eb9-29812ea07101.png)

**Comment by pFernbach** [comment]
The required tag format have changed in an update of the cmake submodule. I have pushed a new tag, you can pull and try again. 

Running` git describe` after a pull should show `v1.3.1-xxxxx` now.

**Comment by TaeilJin** [comment]
Installation is finished after pull, Thank you! 

But there is another issue, after I run the talros_circle.py,  gepetto-gui can't open the .dae file.

![image](https://user-images.githubusercontent.com/41664042/81531476-c60b4f80-939d-11ea-8366-5ad376ecaa1c.png)

Similar error message was also occurred on "Crocoddyl", and at that time, I installed robotpkg-osg-dae to solve.

But it isn't working for this case.

**Comment by wxmerkt** [comment]
You need to install robotpkg-osg-dae if you use robotpkg

**Comment by TaeilJin** [comment]
I already installed the robotkg-osg-dae.

![image](https://user-images.githubusercontent.com/41664042/81535171-492fa400-93a4-11ea-9d1f-afc3d5ccfa70.png)

Could you recommend me another solution?

**Comment by TaeilJin** [comment]
Hi,
I removed everything and reinstalled multicontact-locomotion-planning from github.

I ran gepetto-gui and hpp-rbprm-server, and to run the python code inside “scripts/mlp/demo_configs/”, I typed the following on the command line.

There are errors after I run the demos.

1. python run_mlp.py talos_circle
![image](https://user-images.githubusercontent.com/41664042/82421798-8db1f280-9abc-11ea-8972-dfdfba65b011.png)

2. python run_mlp.py anymal_flatGround
![image](https://user-images.githubusercontent.com/41664042/82421837-a15d5900-9abc-11ea-9b47-c51fbb571271.png)

**Comment by pFernbach** [comment]
Hello, as mentionned above you should use the devel branch of the project because it's the one working with the current binary releases in robotpkg. We are going to merge it in master soon but we need to fix some issues first. 
This should solve your issue with Talos. For anymal it seems that you do not have the robot model and/or the package to use this robot with rbprm. If you need to use anymal I will send you the instructions.

**Comment by TaeilJin** [comment]
Thank you
I should use a devel branch.

Can you send me a instruction for anymal? 

Thanks

Taeil Jin

**Comment by TaeilJin** [comment]
Sorry to keep bothering you,

I checkout the devel branch, and run talos_circle.py
python -im mlp talos_circle

It seems that gepetto-gui and hpp-rbprm-server is running, but there is another error came up on the python.

![image](https://user-images.githubusercontent.com/41664042/82435056-b80cab80-9ace-11ea-8ddc-78b692a8f352.png)

**Comment by pFernbach** [comment]
The scripts in the memmo/ subfolder are for benchmarks and they will write results and logs in a file in `/res/`. If you want to use this scripts you should create this directory with the correct permissions. 

Otherwise I suggest that you use the other scripts in the demos/ subfolder. 

If you want to use this benchmark script and do not want to create a folder in your root directory, you may edit the script but I do not recommend it if you installed them from the binary repository. The concerned files are in `..../lib/python3/dist-packages/hpp/corbaserver/rbprm/scenarios/memmo/`, you can edit the path defined by `self.status_filename`

**Comment by TaeilJin** [comment]
Thank you!

Actually, I want to expand SL1M algorithm, especially I want to generate quadruped motion.

So I want to see anymal walking demonstration using mlp framework.

**Comment by pFernbach** [comment]
It looks like this issue is solved. If you still have installation issues please open another specific issue.
