### ISSUE TITLE
multicontact-api version problem

### ISSUE THREAD

**Issue by muzi2018** [loco-3d/multicontact-locomotion-planning#62]
I have installed the package :
[robotpkg-multicontact-api_2.0.0_amd64.deb](http://robotpkg.openrobots.org/wip/packages/debian/pub/dists/focal/robotpkg/binary-amd64/robotpkg-multicontact-api_2.0.0_amd64.deb)
it is 2.0.0 version but when I compiled the code multicontact-locomotion-planning, it told me that I had a new version 3.0.3, So is it possible that robotpkg-multicontact-api_2.0.0_amd64.deb have some errors ?
`
CMake Error at cmake/package-config.cmake:84 (find_package):
  Could not find a configuration file for package "multicontact-api" that is
  compatible with requested version "2.0".

  The following configuration files were considered but not accepted:

    /opt/openrobots/lib/cmake/multicontact-api/multicontact-apiConfig.cmake, version: 3.0.3

Call Stack (most recent call first):
  CMakeLists.txt:38 (ADD_PROJECT_DEPENDENCY)

`

**Comment by nim65s** [comment]
Hi,

This was fixed in #63. You'll need to switch to the devel branch to get the fix. Getting the latest version of multicontact-api v3.0.3 on robotpkg is working.

**Comment by muzi2018** [comment]
okk, Compile success, Thanks!
